import type { Config } from "tailwindcss";

export default {
  content: [
    "./app/**/*.{js,jsx,ts,tsx}",
    "./components/**/*.{js,jsx,ts,tsx}",
  ],
  presets: [require("nativewind/preset")],
  theme: {
    screens: {
      sm: "640",
      md: "768",
      lg: "1024",
    },
    extend: {
      colors: {
        // Names mirror the deployed Kumo system used by the reference app.
        "kumo-canvas": "#FAFAFA",
        "kumo-elevated": "#F8F8F8",
        "kumo-recessed": "#F3F3F3",
        "kumo-base": "#FFFFFF",
        "kumo-tint": "#F7F7F7",
        "kumo-overlay": "#FAFAFA",
        "kumo-control": "#FFFFFF",
        "kumo-contrast": "#161616",
        "kumo-interact": "#DEDEDE",
        "kumo-fill": "#EBEBEB",
        "kumo-fill-hover": "#F5F5F5",
        "kumo-brand": "#056DFF",
        "kumo-brand-hover": "#005EE6",
        "kumo-info": "#2563EB",
        "kumo-info-tint": "#EFF6FF",
        "kumo-success": "#047857",
        "kumo-success-tint": "#ECFDF5",
        "kumo-warning": "#B45309",
        "kumo-warning-tint": "#FFFBEB",
        "kumo-danger": "#B91C1C",
        "kumo-danger-tint": "#FEF2F2",
        "kumo-default": "#2D2D2D",
        "kumo-strong": "#232323",
        "kumo-subtle": "#808080",
        "kumo-inactive": "#B8B8B8",
        "kumo-placeholder": "#B5B5B5",
        "kumo-inverse": "#F7F7F7",
        "kumo-link": "#2563EB",
        "kumo-line": "#D6D6D6",
        "kumo-hairline": "#E5E5E5",
        // Kumo semantic roles. Keep component classes role-based so the palette can
        // evolve without touching every screen.
        canvas: "#FAFAFA",
        elevated: "#FFFFFF",
        recessed: "#F3F4F6",
        base: "#FFFFFF",
        tint: "#F7F7F8",
        control: "#FFFFFF",
        contrast: "#161616",
        fill: "#E5E7EB",
        "fill-hover": "#DDE1E7",
        background: "#FAFAFA",
        foreground: "#171717",
        primary: {
          DEFAULT: "#056DFF",
          50: "#EFF6FF",
          100: "#DBEAFE",
          200: "#BFDBFE",
          500: "#3B82F6",
          600: "#2563EB",
          700: "#1D4ED8",
        },
        secondary: {
          DEFAULT: "#047857",
          50: "#ECFDF5",
          100: "#D1FAE5",
          500: "#10B981",
          600: "#059669",
        },
        accent: {
          DEFAULT: "#B45309",
          50: "#FFFBEB",
          100: "#FEF3C7",
          500: "#F59E0B",
          600: "#D97706",
        },
        muted: "#E5E7EB",
        border: "#D1D5DB",
        line: "#D1D5DB",
        hairline: "#E5E7EB",
        inverse: "#FAFAFA",
        subtle: "#6B7280",
        inactive: "#9CA3AF",
        placeholder: "#9CA3AF",
        link: "#2563EB",
        info: "#2563EB",
        "info-tint": "#EFF6FF",
        success: "#047857",
        "success-tint": "#ECFDF5",
        warning: "#B45309",
        "warning-tint": "#FFFBEB",
        danger: "#B91C1C",
        "danger-tint": "#FEF2F2",
        gray: {
          50: "#F9FAFB",
          100: "#F3F4F6",
          200: "#E5E7EB",
          300: "#D1D5DB",
          400: "#6B7280",
          500: "#4B5563",
          600: "#374151",
          700: "#1F2937",
          800: "#1F2937",
          900: "#111827",
        },
      },
      fontFamily: {
        sans: ["Outfit_400Regular"],
        "sans-medium": ["Outfit_500Medium"],
        "sans-semibold": ["Outfit_600SemiBold"],
        // Legacy aliases intentionally resolve to the design-system weight.
        // Screens can migrate incrementally without reintroducing heavy display text.
        "sans-bold": ["Outfit_600SemiBold"],
        "sans-extrabold": ["Outfit_600SemiBold"],
      },
      borderRadius: {
        sm: "6px",
        md: "8px",
        lg: "12px",
      },
      boxShadow: {
        kumo: "0 1px 2px 0 rgba(0, 0, 0, 0.08), 0 0 0 1px rgba(0, 0, 0, 0.12)",
        "kumo-primary": "0 1px 2px 0 rgba(0, 0, 0, 0.08), 0 0 0 1px #1741B8",
      },
    },
  },
  plugins: [],
} satisfies Config;
